version: "2"

volumes:
    db_data:

services:
    strichliste:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - db
        restart: always
        ports:
            - 8080:8080
        networks:
            - default
        volumes:
             - ./config/services.yaml:/source/config/services.yaml
    db:
        image: mysql:8.0.16
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 927mwq84g6an6X2c
            MYSQL_DATABASE: strichliste
            MYSQL_USER: sl-user
            MYSQL_PASSWORD: 89s7Adb98A7gJJ61
        volumes:
            - db_data:/var/lib/mysql
